/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "igvsdzbwalohnqxgeuzm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlndnNkemJ3YWxvaG5xeGdldXptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI0NDQ0MzUsImV4cCI6MjA5ODAyMDQzNX0.MwARWopwN8BBJO2Qkw2YGxKKM7NhlBAcbyVsoN-VzWU"
